const ws = {
  PATH_SCRIPT: '/scripts/',
  PATH_CLASSES: '/scripts/classes/',
  PATH_PAGES: '/scripts/pages/',
  PATH_ASSET_IMAGES: '/assets/sources/',
  PATH_METHODS: '/scripts/methods/',
  STORE_CLASSIC_ENTITY: app.classicStore,
  SCRIPT_HOME_PAGE: null,
  SCRIPT_GAME_PAGE: null,
  SCRIPT_ROOM_PAGE: null,
  UPDATE_APP: app.update,
  APP: app,
  CTX: ctx,
  COLOR_BLUE: '#8AB9FF',
  COLOR_GREEN: '#6CFF5E',
  COLOR_RED: '#FF645E',
  COLOR_YELLOW: '#FFCB5E',
  COLOR_WHITE: '#ffffff',
  VERSION: '1.0',
  ZINDEX_UI: 700,
  ZINDEX_ORDER: 1,
  EVENT_ON_FILE_LOADS: () => {},
  EVENT_ON_FILE_LOAD_FINSHED: () => {},
  ASSETS: null,
}